### ISSUE TITLE
Small typo in names

### ISSUE THREAD

**Issue by rafikus** [Booster1212/plugin-farmingsystem#21]
Hey,
I was going through your plugin and noticed `Cooper Ore` I think that is a typo for `Copper`
Other than that great work!

Have you thought of adding some kind of internationalization, so it could be easier to add other languages?

**Comment by Booster1212** [comment]
I wont add localization for items i.e. - Those are just demo icons, you can rename/change it yourself and the script will update it automatically in the database for you.

Other then that, what localization are you talking about elsewise?
